---
- name: stop tomcat
  systemd:
    name: "{{ tomcat_service_name }}"
    state: stopped
  listen: restart tomcat completel
  
- name: start tomcat
  systemd:
    name: "{{ tomcat_service_name }}"
    state: started
  listen: restart tomcat completely